service: import-service-WP

frameworkVersion: "3"
# useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::battiw-shop-be-task5wp"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::battiw-shop-be-task5wp/*"

functions:
  importProductsFileWP:
    handler: handler/importProductsFileWP.importProductsFileWP
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParserWP:
    handler: handler/importFileParserWP.importFileParserWP
    events:
      - s3:
          bucket: battiw-shop-be-task5wp
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: "./webpack.config.cjs" # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: "npm" # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
