service: import-service

frameworkVersion: "3"
# useDotenv: true
# configValidationMode: error

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::battiw-shop-be-task5"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::battiw-shop-be-task5/*"

functions:
  importProductsFile:
    handler: handler/importProductsFile.importProductsFile
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler/importFileParser.importFileParser
    events:
      - s3:
          bucket: battiw-shop-be-task5
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

plugins:
  - serverless-dotenv-plugin
