service: travel-servis-forWebPack

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

functions:
  getProductsListWP:
    handler: handler/getProductsListWP.getProductsListWP
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductsByIdWP:
    handler: handler/getProductsByIdWP.getProductsByIdWP
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true
plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: "./webpack.config.cjs" # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: "npm" # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
