service: product-servis-forWebPack

frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

  environment:
    PG_HOST: $PG_HOST
    PG_PORT: $PG_PORT
    PG_DATABASE: $PG_DATABASE
    PG_USERNAME: $PG_USERNAME
    PG_PASSWORD: $PG_PASSWORD

functions:
  getProductsListTask5WP:
    handler: handler/getProductsListWP.getProductsListWP
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductsByIdTask5WP:
    handler: handler/getProductsByIdWP.getProductsByIdWP
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true
  postProductsTask5:
    handler: handler/postProducts.postProducts
    events:
      - http:
          path: products
          method: post
          cors: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: "./webpack.config.cjs" # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: "npm" # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
