service: travel-servis

frameworkVersion: "3"
useDotenv: true
# configValidationMode: error

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

  environment:
    PG_HOST: $PG_HOST
    PG_PORT: $PG_PORT
    PG_DATABASE: $PG_DATABASE
    PG_USERNAME: $PG_USERNAME
    PG_PASSWORD: $PG_PASSWORD

functions:
  getProductsListTask4:
    handler: handler/getProductsList.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductsByIdTask4:
    handler: handler/getProductsById.getProductsById
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true
  postProductsTask4:
    handler: handler/postProducts.postProducts
    events:
      - http:
          path: products
          method: post
          cors: true
plugins:
  - serverless-dotenv-plugin
