service: travel-servis

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

  environment:
    PG_HOST: db-shop-be.cetpkwcmhoac.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: dbshopbe
    PG_USERNAME: dbshopbe
    PG_PASSWORD: ZMTvLWDr5KXjQvk9eqeX

functions:
  getProductsListTask4:
    handler: handler/getProductsList.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductsByIdTask4:
    handler: handler/getProductsById.getProductsById
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true
